#!/bin/bash
#
echo -n "Sisesta oma vanus:"
read vanus
if [ $vanus -gt 0 -a $vanus -lt 11 ]
then
echo "Oled laps"
elif [ $vanus -ge 11 -a $vanus -lt 18 ]
then
echo "Oled Nooruk"
elif [ $vanus -ge 18 -a $vanus -lt 63 ]
then
echo "Oled täiskasvanu"
elif [ $vanus -ge 63 ]
then
echo "Olen senjoor"
else
echo "Tekkis viga kontrolli sisendit!""
fi
